[package]
name = "chacha"
version = "0.1.0"
authors = ["Peter Reid <peter.d.reid@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies.keystream]
path = "../keystream"

[dependencies]
byteorder = "0.4.*"

[features]
nightly = []
bench = []
